# # Kafka Connect 실행 스크립트를 저장할 디렉토리 생성
# - name: Create directory for sh
#   file:
#     path: /engn/confluent/scripts
#     state: directory
#     owner: ubuntu
#     group: ubuntu
#     mode: '0755'
#     recurse: yes

# # Kafka Connect 시작 스크립트 복사
# - name: Copy Kafka Connect Start Script
#   copy:
#     src: start-connect.sh
#     dest: /engn/confluent/scripts/start-connect.sh
#     owner: ubuntu
#     group: ubuntu
#     mode: '0755'
#   become: true

# # Kafka Connect 종료 스크립트 복사
# - name: Copy Kafka Connect Stop Script
#   copy:
#     src: stop-connect.sh
#     dest: /engn/confluent/scripts/stop-connect.sh
#     owner: ubuntu
#     group: ubuntu
#     mode: '0755'
#   become: true
  

# # Kafka Connect 환경변수 설정
# - name: Ensure CONFLUENT_HOME is present in ~/.bashrc
#   become: true
#   ansible.builtin.lineinfile:
#     path: ~/.bashrc
#     line: 'export CONFLUENT_HOME="/engn/confluent"'
#     state: present
#     create: yes

# - name: Source .bashrc for immediate use (only affects non-login shell)
#   shell: source ~/.bashrc
#   args:
#     executable: /bin/bash
#   ignore_errors: yes  # 셸 프로세스에서 source는 별로 의미가 없어서 무시 처리



# # Kafka Connect 환경변수 설정
# - name: Ensure PROPERTIES_FILE is present in ~/.bashrc
#   become: true
#   ansible.builtin.lineinfile:
#     path: ~/.bashrc
#     line: 'export PROPERTIES_FILE="${CONFLUENT_HOME}/properties/connect-worker.properties"'
#     state: present
#     create: yes

# - name: Source .bashrc for immediate use (only affects non-login shell)
#   shell: source ~/.bashrc
#   args:
#     executable: /bin/bash
#   ignore_errors: yes  # 셸 프로세스에서 source는 별로 의미가 없어서 무시 처리


# # Kafka Connect 설정 파일 디렉토리 생성
# - name: Create directory for Kafka config files
#   file:
#     path: /engn/confluent/properties
#     state: directory
#     owner: ubuntu
#     group: ubuntu
#     mode: '0755'
#     recurse: yes

# Kafka Connect 설정 파일 배포
- name: Deploy connect-worker.properties to instance
  copy:
    src: connect-worker.properties
    dest: /engn/confluent/properties/connect-worker.properties
    owner: ubuntu
    group: ubuntu
    mode: '0644'

# # Kafka Connect 로그 설정 파일 템플릿 배포
# - name: Deploy connect-worker-log4j.properties to instance
#   copy:
#     src: connect-worker-log4j.properties
#     dest: /engn/confluent/properties/connect-worker-log4j.properties
#     owner: ubuntu
#     group: ubuntu
#     mode: '0644'
